name: Deploy Vite App - Sandbox

on:
  workflow_dispatch:

env:
  VITE_NAME: John Doe
  VITE_AGE: 99999

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main

      - name: Install deps
        run: |
          npm install

      - name: Export env variables
        run: |
          echo "VITE_NAME=$VITE_NAME" > .env
          echo "VITE_AGE=$VITE_AGE" > .env

      - name: Build application
        run: |
          npm run build

      - name: Deploy app on server
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yaml
          directory: .ansible/playbooks
          options: |
            --extra-vars ENVIRONMENT=madafaka
